version: 2
models:
  - name: stg_country
    description: "Staging table for country information"
    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null
          - unique

      - name: date_loaded
        description: "Loading date"
        tests:
          - not_null

      - name: country_iso2
        description: "ISO2 country code"

      - name: country_name
        description: "country name"

      - name: income_level
        description: "Country income level"

      - name: lending_type
        description: "Type of lending"

      - name: capital_city
        description: "Country capital"

      - name: capital_lat
        description: "Capital latitud"

      - name: capital_lon
        description: "Capital Longitud"

  - name: stg_indicators
    description: "Information about financial indicators associated to each country"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - year
            - indicator_code

    columns:
      - name: country_code
        description: "ISO3 country code"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_country')
                field: country_code

      - name: indicator_code
        description: "Financial indicator code"
        tests:
          - not_null

      - name: year
        description: "Year of metric"
        tests:
          - not_null

      - name: date_loaded
        description: "Loading date"
        tests:
          - not_null

      - name: indicator_name
        description: "Financial indicator name"

      - name: country_name
        description: "country name"
